---
name: Build and sign EIF
on:
  push:
    tags:
      - "*"

jobs:
  build_and_sign_eif:
    name: Build and sign EIF
    runs-on:
      group: large-nitro-enclave-build-runner-group

    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run build script
        id: run-build-script
        env:
          DOCKER_CONTEXT_DIR: "enclave/"
          DOCKERFILE_PATH: Dockerfile
          EIF_OUTPUT_PATH: ${{ github.workspace }}/eif-output
        shell: bash
        run: ${{ github.workspace }}/.github/workflows/scripts/build-eif.sh

      - name: Github attest
        id: github-attest
        uses: actions/attest-build-provenance@e8998f949152b193b063cb0ec769d69d929409be  # actions/attest-build-provenance@v2.4.0
        with:
          subject-path: '${{ steps.run-build-script.outputs.eif-file-path }}, ${{ steps.run-build-script.outputs.eif-info-path }}'

      - name: Upload to release
        id: upload-to-release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8  # softprops/action-gh-release@v2.3.2
        with:
          files: |
            ${{ steps.run-build-script.outputs.eif-file-path }}
            ${{ steps.run-build-script.outputs.eif-info-path }}
            ${{ steps.github-attest.outputs.bundle-path }}
