---
name: Build and sign EIF
on:
  push:
    branches:
      - main

jobs:
  build_and_sign_eif:
    name: Build and sign EIF
    runs-on:
      group: large-nitro-enclave-build-runner-group

    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df  # aws-actions/configure-aws-credentials@v4.2.1
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}

      - name: Run build script
        id: run-build-script
        env:
          DOCKER_CONTEXT_DIR: "enclave/"
          DOCKERFILE_PATH: Dockerfile
          EIF_OUTPUT_PATH: ${{ github.workspace }}/eif-output
        shell: bash
        run: ${{ github.workspace }}/.github/workflows/scripts/build-eif.sh

      - name: Github attest
        id: github-attest
        uses: actions/attest-build-provenance@e8998f949152b193b063cb0ec769d69d929409be  # actions/attest-build-provenance@v2.4.0
        with:
          subject-path: '${{ steps.run-build-script.outputs.eif-file-path }}, ${{ steps.run-build-script.outputs.eif-info-path }}'

      - name: Upload artifacts to S3
        id: upload-artifacts-to-s3
        env:
          S3_PREFIX: s3://${{ vars.S3_BUCKET_NAME }}/${{ github.sha }}/
          AWS_REGION: ${{ vars.AWS_REGION }}
        shell: bash
        run: |
          aws s3 cp ${{ steps.run-build-script.outputs.eif-file-path }} ${S3_PREFIX}
          aws s3 cp ${{ steps.run-build-script.outputs.eif-info-path }} ${S3_PREFIX}
          aws s3 cp ${{ steps.github-attest.outputs.bundle-path }} ${S3_PREFIX}
